### ISSUE TITLE
Finish Backend Features Part 1

### ISSUE THREAD

**Issue by ShamanthHiremath** [ShamanthHiremath/LibraryManagementSystemGitProject#6]
@sanchiitvijay Pls Finish Backend Features Part 1 in ur branch and raise a PR

**Comment by sanchiitvijay** [comment]
I have submitted Pull Request #10  addressing the issue described above.

Could you please review the changes thoroughly and, if everything is in order, merge it into the main branch?

Your feedback would be greatly appreciated. Thank you!

**Comment by ShamanthHiremath** [comment]
Good work.
Backend Part 1 was merged with no conflicts.
