### ISSUE TITLE
Finish Backend Features Part 2

### ISSUE THREAD

**Issue by ShamanthHiremath** [ShamanthHiremath/LibraryManagementSystemGitProject#7]
@SheikhJaveed  Pls Finish Backend Features Part 2 in ur branch and raise a PR

**Comment by SheikhJaveed** [comment]
completed with backend part 2 @ShamanthHiremath

**Comment by ShamanthHiremath** [comment]
Good work.
Backend Part 2 was merged with no conflicts.
